---
# defaults file for win_rm_kerb_role

#Domain name
krb_realm_name: YOURDOMAIN.LCL
#hostname of Domain Server
krb_kdc_hostname: yourkdc
krb_admin_hostname: youradmin

#defaults for Kerberos
krb_dns_lookup_realm: "true"
krb_dns_lookup_kdc: "true"
krb_ticket_lifetime: "24h"
krb_renew_lifetime: "7d"
krb_forwardable: "true"
krb_rdns : "false"