---
- name: Create automation hub instance
  kubernetes.core.k8s:
    host: "{{ __aap_ocp_install_auth_results['openshift_auth']['host'] }}"
    api_key: "{{ __aap_ocp_install_auth_results['openshift_auth']['api_key'] }}"
    validate_certs: "{{ aap_ocp_install_ocp_connection['validate_certs'] | default(omit) }}"
    state: present
    resource_definition: "{{ lookup('template', 'hub/instance.yaml.j2') | from_yaml }}"
    apply: true

- name: Wait for operator to create the automation hub route
  kubernetes.core.k8s_info:
    host: "{{ __aap_ocp_install_auth_results['openshift_auth']['host'] }}"
    api_key: "{{ __aap_ocp_install_auth_results['openshift_auth']['api_key'] }}"
    validate_certs: "{{ aap_ocp_install_ocp_connection['validate_certs'] | default(omit) }}"
    kind: Route
    name: "{{ aap_ocp_install_hub['instance_name']  | mandatory }}"
    api_version: route.openshift.io/v1
    namespace: "{{ aap_ocp_install_namespace | mandatory }}"
  register: __aap_ocp_install_hub_route_result
  until: __aap_ocp_install_hub_route_result['resources']
  retries: 60  # Wait for 15 minutes (60*15/60)
  delay: 15

- name: Store automation hub route
  ansible.builtin.set_fact:
    __aap_ocp_install_hub_route: "{{ __aap_ocp_install_hub_route_result['resources'][0]['status']['ingress'][0]['host'] }}"

- name: Ensure automation hub login is available
  ansible.builtin.uri:
    url: "https://{{ __aap_ocp_install_hub_route }}"
    validate_certs: "{{ aap_ocp_install_ocp_connection['validate_certs'] | default(omit) }}"
    method: GET
    status_code:
      - 200
  register: __aap_ocp_install_hub_available
  until: __aap_ocp_install_hub_available['status'] == 200
  retries: 120  # Wait for 30 minutes (120*15/60)
  delay: 15

- name: Create automation hub console link
  kubernetes.core.k8s:
    host: "{{ __aap_ocp_install_auth_results['openshift_auth']['host'] }}"
    api_key: "{{ __aap_ocp_install_auth_results['openshift_auth']['api_key'] }}"
    validate_certs: "{{ aap_ocp_install_ocp_connection['validate_certs'] | default(omit) }}"
    state: present
    resource_definition: "{{ lookup('template', 'hub/consolelink.yaml.j2') | from_yaml }}"
    apply: true
...
