---
# Run the Setup to backup AAP
- name: "Run the Ansible AAP Setup Program with backup option"
  become: true
  ansible.builtin.command: ./setup.sh -e 'backup_dest={{ aap_backup_dest | quote }}' -b
  args:
    chdir: "{{ aap_setup_prep_setup_dir }}"
  async: 10000
  poll: 20
  changed_when: false   # these will always run and will always report “changed” otherwise
...
