---
galaxy_info:
  role_name: ansible-tower-install
  author: Tom Page
  description: Role to install Ansible Tower
  company: Red Hat

  license: license (MIT)

  min_ansible_version: 2.7

  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - linux
    - system
    - ansible

dependencies: []
