---
# defaults file for redhat_cop.aap_utilities.aap_remove

############################################################
#               AAP Remove Vars                         #
############################################################

aap_remove_controller: false
aap_remove_ah: false

...
